obstacle_range: 2.5
raytrace_range: 3.0
#footprint: [[x0, y0], [x1, y1], ... [xn, yn]]
#robot_radius: ir_of_robot
inflation_radius: 0.55

observation_sources: point_cloud_sensor

# laser_scan_sensor: {sensor_frame: lidar_wamv_link, data_type: LaserScan, topic: /scan, marking: true, clearing: true}
point_cloud_sensor: {sensor_frame: lidar_wamv_link, data_type: PointCloud2, topic: /lidar_wamv/points, marking: true, clearing: true}